[package]
authors = ["Martin Persson <mnpn03@gmail.com>", "jD91mZM2 <me@krake.one>"]
name = "sardinburk"
version = "0.2.0"
[dependencies]
clap = "2.30.0"
failure = "0.1.5"
rustyline = "1.0.0"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
sslhash = "0.1.1"
